// actionTypes.js

export const ADD_ITEM_TO_CART_REQUEST = 'ADD_ITEM_TO_CART_REQUEST';
export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';
export const ADD_ITEM_TO_CART_FAIL = 'ADD_ITEM_TO_CART_FAIL';
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS';
export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_FAIL';


// constants.js
export const RETRIEVE_CART_ITEMS_REQUEST = 'RETRIEVE_CART_ITEMS_REQUEST';
export const RETRIEVE_CART_ITEMS_SUCCESS = 'RETRIEVE_CART_ITEMS_SUCCESS';
export const RETRIEVE_CART_ITEMS_FAIL = 'RETRIEVE_CART_ITEMS_FAIL';
